"""
VeraSTIX — Step 6: STIX 2.1 Packaging

Takes VALIDATED (Part 4) + REDACTED (Part 5) claims and serializes them
into a real, shareable STIX 2.1 bundle.

Key design decision: the evidence citation doesn't disappear at this
final step. Each Relationship object carries the exact evidence_ids
and confidence level as CUSTOM PROPERTIES (STIX 2.1 allows x_ prefixed
extensions). This means the citation trail survives all the way into
the actual shared output format, not just our internal pipeline — a
recipient of this STIX bundle (or another tool) can see exactly which
evidence justified each claim, which is the whole point of "Vera."
"""

import json
from datetime import datetime, timezone
from stix2 import Malware, AttackPattern, Relationship, Report, Bundle


def build_stix_bundle(sample_name, validated_claims, redaction_note=None):
    malware = Malware(
        name=sample_name,
        is_family=False,
        malware_types=["ransomware"] if any(
            c["technique_id"] == "T1486" for c in validated_claims
        ) else ["unknown"],
    )

    attack_patterns = {}
    relationships = []

    for claim in validated_claims:
        tid = claim["technique_id"]
        if tid not in attack_patterns:
            attack_patterns[tid] = AttackPattern(
                name=claim["technique_name"],
                external_references=[{
                    "source_name": "mitre-attack",
                    "external_id": tid,
                    "url": f"https://attack.mitre.org/techniques/{tid.replace('.', '/')}/",
                }],
            )

        rel = Relationship(
            relationship_type="uses",
            source_ref=malware.id,
            target_ref=attack_patterns[tid].id,
            description=claim.get("justification", ""),
            # Custom properties — this is where the evidence citation
            # actually lives in the final shareable output.
            allow_custom=True,
            x_verastix_evidence_ids=claim.get("evidence_ids", []),
            x_verastix_confidence=claim.get("confidence", "high (direct API evidence chain)"),
        )
        relationships.append(rel)

    objects = [malware] + list(attack_patterns.values()) + relationships

    report_description = "Evidence-grounded threat intelligence generated by VeraSTIX. Every relationship in this bundle cites specific evidence_ids from the source sandbox report, verifiable via the accompanying (internal-only) evidence log."
    if redaction_note:
        report_description += f" {redaction_note}"

    report = Report(
        name=f"VeraSTIX Analysis: {sample_name}",
        description=report_description,
        published=datetime.now(timezone.utc),
        object_refs=[o.id for o in objects],
        labels=["threat-report"],
    )
    objects.append(report)

    return Bundle(objects=objects, allow_custom=True)


if __name__ == "__main__":
    import sys
    claims_path = sys.argv[1] if len(sys.argv) > 1 else "validated_claims.json"
    sample_name = sys.argv[2] if len(sys.argv) > 2 else "unknown_sample"

    validated_claims = json.load(open(claims_path))

    bundle = build_stix_bundle(
        sample_name=sample_name,
        validated_claims=validated_claims,
        redaction_note="Victim-identifying data (usernames, internal IPs, hostnames) has been redacted from the underlying evidence per VeraSTIX's redaction policy; see redaction_manifest_LOCAL_ONLY.json (internal use only, not distributed) for the audit trail.",
    )

    print(f"Built STIX bundle with {len(bundle.objects)} objects:")
    type_counts = {}
    for o in bundle.objects:
        type_counts[o.type] = type_counts.get(o.type, 0) + 1
    for t, c in type_counts.items():
        print(f"  {t}: {c}")

    with open("stix_bundle.json", "w") as f:
        f.write(bundle.serialize(pretty=True))
    print("\nSTIX 2.1 bundle written to stix_bundle.json — this is the final shareable deliverable.")
